[package]
name = "wdt-module-firefox"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
wdt-module-api = { path = "../api" }
wdt-logging = { path = "../../logging" }
