[package]
name = "wdt-module-software"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
wdt-module-api = { path = "../api" }
wdt-logging = { path = "../../logging" }
serde = { version = "1", features = ["derive"] }
msi = "0.2.0"
thiserror = "1"
